/**
SCRIPT SIMPLIFICADO PARA LA ACTIVIDAD 29 DE TCS
**/

CREATE TABLE PUNTUACION(
    IDCLIENTE INTEGER NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    PUNTUACION INTEGER,
    PRIMARY KEY (IDCLIENTE)
);